<a href="https://colab.research.google.com/github/mmentella/neuron/blob/master/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf

c = tf.constant([[[1.0, 2.0], [3.0, 4.0]],[[1.0, 2.0], [3.0, 4.0]]])
d = tf.constant([[[5.0, 6.0], [7.0, 8.0]],[[5.0, 6.0], [7.0, 8.0]]])

tf.tensordot(c,d,[[1],[1]])

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[26., 30.],
         [26., 30.]],

        [[38., 44.],
         [38., 44.]]],


       [[[26., 30.],
         [26., 30.]],

        [[38., 44.],
         [38., 44.]]]], dtype=float32)>

In [23]:
import tensorflow as tf

a = tf.constant([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
b = tf.constant([[1,2],[3,4]])
print(a)
print(b)

c = tf.tensordot(a,b,1)
print(c)
d = tf.tensordot(a,b,[[0],[0]])
print(d)

tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]], shape=(2, 3, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[ 7 10]
  [15 22]
  [23 34]]

 [[ 7 10]
  [15 22]
  [23 34]]], shape=(2, 3, 2), dtype=int32)
tf.Tensor(
[[[ 4  6]
  [ 8 12]]

 [[12 18]
  [16 24]]

 [[20 30]
  [24 36]]], shape=(3, 2, 2), dtype=int32)


In [4]:
import tensorflow as tf

a = tf.constant([[[1,2],[3,4]],[[1,2],[3,4]]])
print(a)
b = a
print(b)

c = tf.tensordot(a,b,[[0],[0]])
print(c)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(
[[[[ 2  4]
   [ 6  8]]

  [[ 4  8]
   [12 16]]]


 [[[ 6 12]
   [18 24]]

  [[ 8 16]
   [24 32]]]], shape=(2, 2, 2, 2), dtype=int32)
